---
# Variables for the workstations group

# Local user configuration
local_user: "arcangelo"

# Fedora bloatware packages to remove
fedora_bloatware:
  - gnome-boxes
  - gnome-contacts
  - gnome-maps
  - gnome-tour
  - gnome-weather
  - rhythmbox
  - totem
  - yelp
  - gnome-calculator
  - simple-scan
  - gnome-connections
  - gnome-clocks
  - cheese
  - snapshot
  - firefox-langpacks
  - firefox

# Common packages to install
common_packages:
  - git
  - htop
  - tilix
  - wget
  - curl

# Development packages to install
development_packages:
  - gcc
  - gcc-c++
  - make
  - automake
  - autoconf
  - python3-devel
  - python3-pip
  - nodejs
  - npm
  - nano

# Git configuration
git_config:
  user:
    name: "arcangelo7"
    email: "arcangelomas@gmail.com"
  core:
    editor: "nano"

# Desktop configuration
desktop_theme: "Arc-Dark"
desktop_icon_theme: "Papirus-Dark"
desktop_dark_mode: true

# Flatpak bloatware packages to remove
flatpak_bloatware:
  - org.fedoraproject.MediaWriter
