---
# Variabili per il gruppo workstations

# Pacchetti comuni da installare
common_packages:
  - git
  - htop
  - tilix
  - wget
  - curl

# Pacchetti di sviluppo da installare
development_packages:
  - gcc
  - gcc-c++
  - make
  - automake
  - autoconf
  - python3-devel
  - python3-pip
  - nodejs
  - npm
  - nano

# Configurazione Git
git_config:
  user:
    name: "arcangelo7"
    email: "arcangelomas@gmail.com"
  core:
    editor: "nano"

# Configurazione desktop
desktop_theme: "Arc-Dark"
desktop_icon_theme: "Papirus-Dark"
desktop_dark_mode: true 