---
- name: Configure Fedora Workstation
  hosts: workstations
  become: true
  vars_files:
    - group_vars/vault/joplin.yml
  
  roles:
    - common
    - development
    - desktop
    - applications