---
# Install themes and icons
- name: Install gnome-tweaks
  dnf:
    name:
      - gnome-tweaks
    state: present
  tags:
    - desktop
    - themes

# Install GNOME extensions
- name: Install GNOME extensions
  dnf:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
      - gnome-extensions-app
    state: present
  tags:
    - desktop
    - gnome-extensions

# Install Brave Browser from Flatpak
- name: Ensure Flatpak is installed
  dnf:
    name: flatpak
    state: present
  become: yes
  tags:
    - desktop
    - browser
    - brave

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: yes
  tags:
    - desktop
    - browser
    - brave

- name: Install Brave Browser from Flathub
  command: flatpak install -y flathub com.brave.Browser
  become: yes
  tags:
    - desktop
    - browser
    - brave