---
# Check if gnome-tweaks is already installed
- name: Check if gnome-tweaks is installed
  command: rpm -q gnome-tweaks
  register: gnome_tweaks_check
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - desktop
    - themes

# Install themes and icons
- name: Install gnome-tweaks
  dnf:
    name:
      - gnome-tweaks
    state: present
  when: gnome_tweaks_check.rc != 0
  tags:
    - desktop
    - themes

# Check if GNOME extensions are already installed
- name: Check installed GNOME extensions
  command: rpm -q gnome-shell-extension-appindicator gnome-shell-extension-dash-to-dock gnome-extensions-app
  register: gnome_extensions_check
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - desktop
    - gnome-extensions

# Install GNOME extensions
- name: Install GNOME extensions
  dnf:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
      - gnome-extensions-app
    state: present
  when: gnome_extensions_check.rc != 0
  tags:
    - desktop
    - gnome-extensions

# Verify if Flatpak is installed
- name: Check if Flatpak is installed
  command: which flatpak
  register: flatpak_check
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - desktop
    - browser

# Install Flatpak
- name: Ensure Flatpak is installed
  dnf:
    name: flatpak
    state: present
  become: yes
  when: flatpak_check.rc != 0
  tags:
    - desktop
    - browser

# Check if Flathub repository is already added
- name: Check if Flathub repository is added
  command: flatpak remote-list
  register: flathub_check
  changed_when: false
  check_mode: no
  tags:
    - desktop
    - browser

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: yes
  when: "'flathub' not in flathub_check.stdout"
  tags:
    - desktop
    - browser

# Check if Thunderbird is already installed
- name: Check if Thunderbird is installed
  command: rpm -q thunderbird
  register: thunderbird_check
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - desktop
    - email
    - thunderbird

# Install Thunderbird
- name: Install Thunderbird email client
  dnf:
    name: thunderbird
    state: present
  when: thunderbird_check.rc != 0
  tags:
    - desktop
    - email
    - thunderbird