---
# Installa temi e icone
- name: Installa gnome-tweaks
  dnf:
    name:
      - gnome-tweaks
    state: present
  tags:
    - desktop
    - themes

# Installa estensioni GNOME
- name: Installa estensioni GNOME
  dnf:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
      - gnome-extensions-app
    state: present
  tags:
    - desktop
    - gnome-extensions

# Installa Brave Browser da Flatpak
- name: Assicurati che Flatpak sia installato
  dnf:
    name: flatpak
    state: present
  become: yes
  tags:
    - desktop
    - browser
    - brave

- name: Aggiungi repository Flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: yes
  tags:
    - desktop
    - browser
    - brave

- name: Installa Brave Browser da Flathub
  command: flatpak install -y flathub com.brave.Browser
  become: yes
  tags:
    - desktop
    - browser
    - brave