---
# Default variables for development role

# Cursor AppImage
cursor_appimage_url: "https://downloads.cursor.com/production/b6fb41b5f36bda05cab7109606e7404a65d1ff32/linux/x64/Cursor-0.47.9-x86_64.AppImage"
cursor_appimage_dest: "/opt/appimages/Cursor.AppImage"
cursor_icon_dest: "/usr/share/icons/hicolor/256x256/apps/cursor.png"
cursor_desktop_entry_dest: "/usr/share/applications/cursor.desktop"
cursor_metadata_file: "/opt/appimages/cursor.version"
appimages_dir: "/opt/appimages" 

# Windsurf AI
windsurf_tarball_url: "https://windsurf-stable.codeiumdata.com/linux-x64/stable/5345eec411f91303b5d1abad6a0b991f78caf8d5/Windsurf-linux-x64-1.5.8.tar.gz"
windsurf_install_dir: "/opt/windsurf"
windsurf_binary_path: "{{ windsurf_install_dir }}/Windsurf/windsurf"
windsurf_icon_dest: "/usr/share/icons/hicolor/256x256/apps/windsurf.png"
windsurf_desktop_entry_dest: "/usr/share/applications/windsurf.desktop"
windsurf_metadata_file: "{{ windsurf_install_dir }}/windsurf.version"
windsurf_tarball_dest: "/tmp/windsurf.tar.gz" 