---
uv_version: "0.6.14"
uv_platform: "x86_64-unknown-linux-musl"
uv_download_url: "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-{{ uv_platform }}.tar.gz"
uv_checksum: "sha256:0cac4df0cb3457b154f2039ae471e89cd4e15f3bd790bbb3cb0b8b40d940b93e"
uv_install_path: "/usr/local/bin/uv"
uv_tmp_archive: "/tmp/uv-{{ uv_version }}.tar.gz"
uv_tmp_extract_dir: "/tmp/uv-{{ uv_version }}-extract"
android_studio_version: "2024.2.1.11"
android_studio_download_url: "https://redirector.gvt1.com/edgedl/android/studio/ide-zips/{{ android_studio_version }}/android-studio-{{ android_studio_version }}-linux.tar.gz"
android_studio_install_dir: "/opt/android-studio"
android_studio_desktop_entry_dest: "/usr/share/applications/android-studio.desktop"
android_studio_tmp_archive: "/tmp/android-studio-{{ android_studio_version }}.tar.gz"
android_studio_tmp_extract_dir: "/tmp/android-studio-extract"
android_cmdline_tools_version: "11076708"
android_cmdline_tools_url: "https://dl.google.com/android/repository/commandlinetools-linux-{{ android_cmdline_tools_version }}_latest.zip"
android_cmdline_tools_archive: "/tmp/commandlinetools-linux-{{ android_cmdline_tools_version }}.zip"
android_cmdline_tools_extract_dir: "/tmp/cmdline-tools-extract"
android_sdk_dir: "/home/{{ local_user }}/Android/Sdk"
android_cmdline_tools_dir: "{{ android_sdk_dir }}/cmdline-tools/latest"
flutter_packages:
  - egl-utils