---
# Install Discord from Flathub
- name: Check if Flathub is enabled
  command: flatpak remotes --columns=name
  register: flatpak_remotes
  changed_when: false
  tags:
    - applications
    - discord

- name: Enable Flathub if not already enabled
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  when: "'flathub' not in flatpak_remotes.stdout"
  tags:
    - applications
    - discord

- name: Check if Discord is already installed
  command: flatpak list --app --columns=application
  register: installed_flatpaks
  changed_when: false
  tags:
    - applications
    - discord

# Install Discord Flatpak
- name: Install Discord Flatpak
  community.general.flatpak:
    name: "{{ discord_flatpak_app_id }}"
    state: present
  tags:
    - applications
    - discord

# Install VLC Flatpak
- name: Install VLC Flatpak
  community.general.flatpak:
    name: "{{ vlc_flatpak_app_id }}"
    state: present
  tags:
    - applications
    - vlc

# Install openfortivpn
- name: Install openfortivpn package
  dnf:
    name: openfortivpn
    state: present
  tags:
    - applications
    - vpn
    - openfortivpn

# Add VPN alias to user's .bashrc
- name: Check if vpnunibo alias already exists in .bashrc
  shell: grep -q "^alias vpnunibo=" "/home/{{ local_user }}/.bashrc"
  register: vpnunibo_alias_check
  failed_when: false
  changed_when: false
  become: false
  tags:
    - applications
    - vpn
    - openfortivpn

- name: Add vpnunibo alias to .bashrc
  lineinfile:
    path: "/home/{{ local_user }}/.bashrc"
    line: "alias vpnunibo='sudo openfortivpn vpn.unibo.it:443 -u arcangelo.massari@unibo.it'"
    state: present
  when: vpnunibo_alias_check.rc != 0
  become: false
  tags:
    - applications
    - vpn
    - openfortivpn 