---
# Install Cursor AppImage
- name: Create directory for AppImages
  file:
    path: "{{ appimages_dir }}"
    state: directory
    mode: '0755'
  tags:
    - applications
    - cursor

- name: Download Cursor AppImage
  get_url:
    url: "{{ cursor_appimage_url }}"
    dest: "{{ cursor_appimage_dest }}"
    mode: '0755'
  tags:
    - applications
    - cursor

- name: Create temporary directory for AppImage extraction
  file:
    path: /tmp/cursor-extract
    state: directory
    mode: '0755'
  tags:
    - applications
    - cursor

- name: Extract AppImage to get icon
  command: "{{ cursor_appimage_dest }} --appimage-extract"
  args:
    chdir: /tmp/cursor-extract
    creates: /tmp/cursor-extract/squashfs-root
  tags:
    - applications
    - cursor

- name: Find icon file
  find:
    paths: /tmp/cursor-extract/squashfs-root
    patterns: "*.png,*.svg,*.ico"
    recurse: yes
  register: icon_files
  tags:
    - applications
    - cursor

- name: Create icons directory if it doesn't exist
  file:
    path: "{{ cursor_icon_dest | dirname }}"
    state: directory
    mode: '0755'
  tags:
    - applications
    - cursor

- name: Copy icon to system icons directory
  copy:
    src: "{{ icon_files.files[0].path }}"
    dest: "{{ cursor_icon_dest }}"
    mode: '0644'
    remote_src: yes
  when: icon_files.files | length > 0
  tags:
    - applications
    - cursor

- name: Create desktop entry for Cursor
  template:
    src: cursor.desktop.j2
    dest: "{{ cursor_desktop_entry_dest }}"
    mode: '0644'
  tags:
    - applications
    - cursor

# Add Cursor to PATH
- name: Create bin directory if it doesn't exist
  file:
    path: "{{ bin_dir | default('/usr/local/bin') }}"
    state: directory
    mode: '0755'
  become: true
  tags:
    - applications
    - cursor

- name: Create symbolic link to Cursor in PATH
  file:
    src: "{{ cursor_appimage_dest }}"
    dest: "{{ bin_dir | default('/usr/local/bin') }}/cursor"
    state: link
  become: true
  tags:
    - applications
    - cursor

- name: Clean up temporary extraction directory
  file:
    path: /tmp/cursor-extract
    state: absent
  tags:
    - applications
    - cursor 