---
# Default MIME type associations

video_player_app: "org.videolan.VLC.desktop"

video_mime_types:
  - "video/mp4"
  - "video/x-matroska"          # MKV
  - "video/quicktime"            # MOV
  - "video/x-msvideo"            # AVI
  - "video/webm"
  - "video/mpeg"
  - "video/x-flv"
  - "video/3gpp"
  - "video/ogg"
  - "video/x-ms-wmv"

text_editor_app: "code.desktop"

text_mime_types:
  - "text/plain"
  - "text/markdown"
  - "text/x-python"
  - "text/x-java"
  - "text/x-c"
  - "text/x-c++"
  - "text/x-shellscript"
  - "text/javascript"
  - "text/css"
  - "text/html"
  - "application/json"
  - "application/xml"
  - "application/x-yaml"
  - "text/x-ruby"
  - "text/x-go"
  - "text/x-rust"

image_editor_app: "com.github.PintaProject.Pinta.desktop"

image_mime_types:
  - "image/png"
  - "image/jpeg"
  - "image/jpg"
  - "image/gif"
  - "image/bmp"
  - "image/webp"
  - "image/tiff"
  - "image/x-icon"

vector_graphics_app: "org.inkscape.Inkscape.desktop"

vector_graphics_mime_types:
  - "image/svg+xml"
  - "image/svg+xml-compressed"

pdf_viewer_app: "okularApplication_pdf.desktop"

pdf_mime_types:
  - "application/pdf"

office_suite_app: "org.libreoffice.LibreOffice.desktop"

document_mime_types:
  - "application/vnd.oasis.opendocument.text"         # ODT
  - "application/vnd.oasis.opendocument.spreadsheet"  # ODS
  - "application/vnd.oasis.opendocument.presentation" # ODP
  - "application/msword"                               # DOC
  - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"   # DOCX
  - "application/vnd.ms-excel"                         # XLS
  - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"        # XLSX
  - "application/vnd.ms-powerpoint"                    # PPT
  - "application/vnd.openxmlformats-officedocument.presentationml.presentation" # PPTX
  - "text/rtf"

web_browser_app: "com.brave.Browser.desktop"

web_mime_types:
  - "x-scheme-handler/http"
  - "x-scheme-handler/https"
  - "x-scheme-handler/ftp"
  - "x-scheme-handler/chrome"
  - "application/x-extension-htm"
  - "application/x-extension-html"
  - "application/x-extension-shtml"
  - "application/xhtml+xml"
  - "application/x-extension-xhtml"
  - "application/x-extension-xht"

torrent_client_app: "org.qbittorrent.qBittorrent.desktop"

torrent_mime_types:
  - "application/x-bittorrent"
  - "x-scheme-handler/magnet"
