---
# Default variables for applications role

# Cursor AppImage
cursor_appimage_url: "https://downloads.cursor.com/production/82ef0f61c01d079d1b7e5ab04d88499d5af500e3/linux/x64/Cursor-0.47.8-82ef0f61c01d079d1b7e5ab04d88499d5af500e3.deb.glibc2.25-x86_64.AppImage"
cursor_appimage_dest: "/opt/appimages/Cursor.AppImage"
cursor_icon_dest: "/usr/share/icons/hicolor/256x256/apps/cursor.png"
cursor_desktop_entry_dest: "/usr/share/applications/cursor.desktop"
cursor_metadata_file: "/opt/appimages/cursor.version"
appimages_dir: "/opt/appimages" 

# Discord Flatpak
discord_flatpak_app_id: "com.discordapp.Discord" 

# VLC Flatpak
vlc_flatpak_app_id: "org.videolan.VLC" 