---
# Default variables for applications role

discord_flatpak_app_id: "com.discordapp.Discord" 

firefox_flatpak_app_id: "org.mozilla.firefox"

vlc_flatpak_app_id: "org.videolan.VLC"

pinta_flatpak_app_id: "com.github.PintaProject.Pinta"

inkscape_flatpak_app_id: "org.inkscape.Inkscape"

zoom_flatpak_app_id: "us.zoom.Zoom"

stremio_flatpak_app_id: "com.stremio.Stremio"

telegram_flatpak_app_id: "org.telegram.desktop"

spotify_flatpak_app_id: "com.spotify.Client"

joplin_appimage_url: "https://github.com/laurent22/joplin/releases/download/v3.2.13/Joplin-3.2.13.AppImage"
joplin_appimage_dest: "/opt/appimages/Joplin.AppImage"
joplin_icon_dest: "/usr/share/icons/hicolor/256x256/apps/joplin.png"
joplin_desktop_entry_dest: "/usr/share/applications/joplin.desktop"
joplin_metadata_file: "/opt/appimages/joplin.version"
appimages_dir: "/opt/appimages"
bin_dir: "/usr/local/bin"

joplin_sync_target: 5  # 5 per WebDAV
joplin_sync_webdav_path: "https://cloud.arcangelomassari.com/remote.php/dav/files/arcangelo/Documents/Joplin/"
joplin_sync_webdav_username: "arcangelo"
joplin_sync_webdav_password: "{{ vault_joplin_webdav_password | default('') }}"  # Da definire in .env

jimmy_download_url: "https://github.com/marph91/jimmy/releases/latest/download/jimmy-linux"
jimmy_install_path: "/usr/local/bin/jimmy"

btrfs_assistant_package_name: "btrfs-assistant"

google_chrome_repo_url: "https://dl.google.com/linux/chrome/rpm/stable/x86_64"
google_chrome_package_name: "google-chrome-stable"

conky_version: "1.22.1"
conky_source_url: "https://github.com/brndnmtthws/conky/archive/refs/tags/v{{ conky_version }}.tar.gz"
conky_build_dir: "/tmp/conky-build"
conky_src_dir: "{{ conky_build_dir }}/conky-{{ conky_version }}"
conky_resolution: "qhd"

libreoffice_flatpak_app_id: "org.libreoffice.LibreOffice"

brave_flatpak_app_id: "com.brave.Browser"

zotero_flatpak_app_id: "org.zotero.Zotero"

portfolio_version: "1.8.4"
portfolio_download_url: "https://github.com/arcangelo7/portfolio/releases/download/v{{portfolio_version}}/portfolio-linux-{{portfolio_version}}.tar.gz"
portfolio_archive: "/tmp/portfolio-linux-{{ portfolio_version }}.tar.gz"
portfolio_extract_dir: "/tmp/portfolio-extract"
portfolio_metadata_file: "/opt/appimages/portfolio.version"

texlive_packages:
  - "texlive-collection-latex"
  - "texlive-collection-latexrecommended"
  - "latexmk"

okular_package_name: "okular"