---
# Default variables for applications role

# Discord Flatpak
discord_flatpak_app_id: "com.discordapp.Discord" 

# VLC Flatpak
vlc_flatpak_app_id: "org.videolan.VLC" 

# Drawing Flatpak
drawing_flatpak_app_id: "com.github.maoschanz.drawing"

# Joplin Flatpak
joplin_flatpak_app_id: "net.cozic.joplin_desktop"

# Joplin CLI
joplin_cli_package_name: "joplin-cli"

# Btrfs Assistant
btrfs_assistant_package_name: "btrfs-assistant"

# Google Chrome
google_chrome_repo_url: "https://dl.google.com/linux/chrome/rpm/stable/x86_64"
google_chrome_package_name: "google-chrome-stable"