---
# Default variables for applications role

# Cursor AppImage
cursor_appimage_url: "https://downloads.cursor.com/production/client/linux/x64/appimage/Cursor-0.46.11-ae378be9dc2f5f1a6a1a220c6e25f9f03c8d4e19.deb.glibc2.25-x86_64.AppImage"
cursor_appimage_dest: "/opt/appimages/Cursor.AppImage"
cursor_icon_dest: "/usr/share/icons/hicolor/256x256/apps/cursor.png"
cursor_desktop_entry_dest: "/usr/share/applications/cursor.desktop"
appimages_dir: "/opt/appimages" 

# Discord Flatpak
discord_flatpak_app_id: "com.discordapp.Discord" 