---
# Update the system
- name: Update all packages
  dnf:
    name: "*"
    state: latest
  tags:
    - system
    - update

# Install base packages
- name: Install base packages
  dnf:
    name: "{{ common_packages }}"
    state: present
  tags:
    - packages
    - base-packages 